{
 "title": "VeChain Blocks",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "main,test" }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "query": "select elapsed(num,1s) as interval from blocks where time > now() - 5m and network='$network'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "query": "select difference(totalScore) from (select top(totalScore, 2) as totalScore from blocks where time > now() - 5m and network='$network')",
     "select": [
      [
       { "params": [ "totalScore" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "query": "select sum(paid)/sum(gasUsed)*1000/1000000000000000000 from (select gasUsed,paid from blocks where gasUsed > 0 and network='$network' order by time desc limit 10) order by time desc",
     "select": [
      [
       { "params": [ "paid" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "targets": [
    {
     "alias": "CPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "query": "SELECT \"gasLimit\"  / 16000 / 10 FROM \"blocks\" WHERE time > now() - 5m and network='$network'",
     "select": [
      [
       { "params": [ "gasLimit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 16000 / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "query": "SELECT sum(\"clauseCount\")/(last(timestamp) - first(timestamp)) FROM \"blocks\" WHERE time > now() - 5m and network='$network'\n",
     "select": [
      [
       { "params": [ "clauseCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Txs/Clauses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 2, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Clauses",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "query": "SELECT sum(\"clauseCount\") FROM \"blocks\" WHERE (\"network\" =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "clauseCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Txs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "select": [
      [
       { "params": [ "txCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "VIP191",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "select": [
      [
       { "params": [ "vip191TxCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "MPP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "select": [
      [
       { "params": [ "mppTxCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Reverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "select": [
      [
       { "params": [ "revertedTxCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Gas Limit/Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Gas Limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "query": "SELECT max(\"gasLimit\") FROM \"blocks\" WHERE (\"network\" =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "gasLimit" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Gas Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "select": [
      [
       { "params": [ "gasUsed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Block Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 2, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Score",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "query": "SELECT min(\"score\") as \"score\"  FROM (SELECT difference(\"totalScore\") as \"score\" FROM \"blocks\" where network='$network') WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_score" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Interval",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"blockInterval\") as \"blockInterval\" FROM (SELECT elapsed(\"num\", 1s) as \"blockInterval\" FROM \"blocks\" where network='$network') WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transfers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "VET Amount",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocks",
     "select": [
      [
       { "params": [ "transferAmount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "network", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Energy Burned",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 2, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"paid\") * 0.7 / 1000000000000000000 / 1000000000 from blocks where network='$network'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}